# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/hello_world/hello_world.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import core.service_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='example/hello_world/hello_world.proto',
  package='example',
  serialized_pb=_b('\n%example/hello_world/hello_world.proto\x12\x07\x65xample\x1a\x12\x63ore/service.proto\"H\n\x0cHelloRequest\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.core.ServiceRequestHeader\x12\x0c\n\x04name\x18\x02 \x01(\t\"M\n\rHelloResponse\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.core.ServiceResponseHeader\x12\x0f\n\x07message\x18\x02 \x01(\t')
  ,
  dependencies=[core.service_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='example.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='example.HelloRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='example.HelloRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=142,
)


_HELLORESPONSE = _descriptor.Descriptor(
  name='HelloResponse',
  full_name='example.HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='example.HelloResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='example.HelloResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=221,
)

_HELLOREQUEST.fields_by_name['header'].message_type = core.service_pb2._SERVICEREQUESTHEADER
_HELLORESPONSE.fields_by_name['header'].message_type = core.service_pb2._SERVICERESPONSEHEADER
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'example.hello_world.hello_world_pb2'
  # @@protoc_insertion_point(class_scope:example.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), dict(
  DESCRIPTOR = _HELLORESPONSE,
  __module__ = 'example.hello_world.hello_world_pb2'
  # @@protoc_insertion_point(class_scope:example.HelloResponse)
  ))
_sym_db.RegisterMessage(HelloResponse)


# @@protoc_insertion_point(module_scope)
