# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: publishing/services/hello_world/hello_world.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='publishing/services/hello_world/hello_world.proto',
  package='publishing.services.example',
  serialized_pb=_b('\n1publishing/services/hello_world/hello_world.proto\x12\x1bpublishing.services.example\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"~\n\rHelloResponse\x12\x41\n\x06header\x18\x01 \x01(\x0b\x32\x31.publishing.services.example.HelloResponse.Header\x12\x0f\n\x07message\x18\x02 \x01(\t\x1a\x19\n\x06Header\x12\x0f\n\x07success\x18\x01 \x01(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='publishing.services.example.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='publishing.services.example.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=110,
)


_HELLORESPONSE_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='publishing.services.example.HelloResponse.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='publishing.services.example.HelloResponse.Header.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=238,
)

_HELLORESPONSE = _descriptor.Descriptor(
  name='HelloResponse',
  full_name='publishing.services.example.HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='publishing.services.example.HelloResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='publishing.services.example.HelloResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_HELLORESPONSE_HEADER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=238,
)

_HELLORESPONSE_HEADER.containing_type = _HELLORESPONSE
_HELLORESPONSE.fields_by_name['header'].message_type = _HELLORESPONSE_HEADER
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'publishing.services.hello_world.hello_world_pb2'
  # @@protoc_insertion_point(class_scope:publishing.services.example.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), dict(

  Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
    DESCRIPTOR = _HELLORESPONSE_HEADER,
    __module__ = 'publishing.services.hello_world.hello_world_pb2'
    # @@protoc_insertion_point(class_scope:publishing.services.example.HelloResponse.Header)
    ))
  ,
  DESCRIPTOR = _HELLORESPONSE,
  __module__ = 'publishing.services.hello_world.hello_world_pb2'
  # @@protoc_insertion_point(class_scope:publishing.services.example.HelloResponse)
  ))
_sym_db.RegisterMessage(HelloResponse)
_sym_db.RegisterMessage(HelloResponse.Header)


# @@protoc_insertion_point(module_scope)
